{"name": "Login User with Incorrect Credentials", "status": "passed", "description": "Verify error message appears when user logs in with invalid email/password.", "attachments": [{"name": "log", "source": "7769976f-79bd-4060-b83d-aac58f0f0a12-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "ec61185e-62b7-40b3-9809-64d5a488d228-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "697f35e0-e0d3-4e37-94fc-7830c1a340d7-attachment.txt", "type": "text/plain"}], "start": 1747938897583, "stop": 1747938899901, "uuid": "57e8472b-0bb7-460c-a80c-d7c18ac62cfc", "historyId": "8dfedac07557eef94db876c5511d4142", "testCaseId": "8dfedac07557eef94db876c5511d4142", "fullName": "testCases.test_003_login_incorrect_credentials#test_003_login_user_with_incorrect_credentials", "labels": [{"name": "feature", "value": "User Authentication"}, {"name": "severity", "value": "normal"}, {"name": "parentSuite", "value": "testCases"}, {"name": "suite", "value": "test_003_login_incorrect_credentials"}, {"name": "host", "value": "DESKTOP-6JB123S"}, {"name": "thread", "value": "16640-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCases.test_003_login_incorrect_credentials"}]}