{"name": "Login User with Incorrect Credentials", "status": "passed", "description": "Verify error message appears when user logs in with invalid email/password.", "attachments": [{"name": "log", "source": "d56e84ad-ce78-4b56-ad7d-e221c6c847a7-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "01779e72-7fd1-41e5-8c75-50c08a1f33a3-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "26b930cf-6f3e-4d10-8178-accbbb54c9e9-attachment.txt", "type": "text/plain"}], "start": 1748283148287, "stop": 1748283150456, "uuid": "e715d904-12d0-4070-81c1-01cec4825c5b", "historyId": "8dfedac07557eef94db876c5511d4142", "testCaseId": "8dfedac07557eef94db876c5511d4142", "fullName": "testCases.test_003_login_incorrect_credentials#test_003_login_user_with_incorrect_credentials", "labels": [{"name": "feature", "value": "User Authentication"}, {"name": "severity", "value": "normal"}, {"name": "parentSuite", "value": "testCases"}, {"name": "suite", "value": "test_003_login_incorrect_credentials"}, {"name": "host", "value": "DESKTOP-6JB123S"}, {"name": "thread", "value": "5056-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCases.test_003_login_incorrect_credentials"}]}