{"uuid": "e9a55756-b6f8-492e-9627-3cb4b357564e", "children": ["416fdb11-7d20-4991-bcb1-318a75ee226c"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_NAME_NOT_RESOLVED\n  (Session info: chrome=136.0.7103.114)\nStacktrace:\n\tGetHandleVerifier [0x00D9FC03+61635]\n\tGetHandleVerifier [0x00D9FC44+61700]\n\t(No symbol) [0x00BC05D3]\n\t(No symbol) [0x00BBDBE0]\n\t(No symbol) [0x00BB13A8]\n\t(No symbol) [0x00BB2CF0]\n\t(No symbol) [0x00BB1638]\n\t(No symbol) [0x00BB1193]\n\t(No symbol) [0x00BB0EA1]\n\t(No symbol) [0x00BAEE80]\n\t(No symbol) [0x00BAF81B]\n\t(No symbol) [0x00BC3FFE]\n\t(No symbol) [0x00C4F217]\n\t(No symbol) [0x00C2D29C]\n\t(No symbol) [0x00C4E61B]\n\t(No symbol) [0x00C2D096]\n\t(No symbol) [0x00BFC840]\n\t(No symbol) [0x00BFD6A4]\n\tGetHandleVerifier [0x01024523+2701795]\n\tGetHandleVerifier [0x0101FCA6+2683238]\n\tGetHandleVerifier [0x0103A9EE+2793134]\n\tGetHandleVerifier [0x00DB68C5+155013]\n\tGetHandleVerifier [0x00DBCFAD+181357]\n\tGetHandleVerifier [0x00DA7458+92440]\n\tGetHandleVerifier [0x00DA7600+92864]\n\tGetHandleVerifier [0x00D91FF0+5296]\n\tBaseThreadInitThunk [0x757BFCC9+25]\n\tRtlGetAppContainerNamedObjectPath [0x779782AE+286]\n\tRtlGetAppContainerNamedObjectPath [0x7797827E+238]\n\n", "trace": "  File \"D:\\automation-exercise-webapp\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\automation-exercise-webapp\\venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"D:\\automation-exercise-webapp\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\automation-exercise-webapp\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\automation-exercise-webapp\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"D:\\automation-exercise-webapp\\conftest.py\", line 70, in browser\n    driver.get(config.BASE_URL)\n  File \"D:\\automation-exercise-webapp\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 454, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"D:\\automation-exercise-webapp\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\automation-exercise-webapp\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1748710130663, "stop": 1748710137925}], "start": 1748710130663, "stop": 1748710137982}