{"uuid": "1c5c0cbb-45f2-47f9-903c-8668f5ea0efa", "children": ["5a0ddadc-a311-4675-9bf2-9dd64e260e2e"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_NAME_NOT_RESOLVED\n  (Session info: chrome=136.0.7103.114)\nStacktrace:\n\tGetHandleVerifier [0x009FFC03+61635]\n\tGetHandleVerifier [0x009FFC44+61700]\n\t(No symbol) [0x008205D3]\n\t(No symbol) [0x0081DBE0]\n\t(No symbol) [0x008113A8]\n\t(No symbol) [0x00812CF0]\n\t(No symbol) [0x00811638]\n\t(No symbol) [0x00811193]\n\t(No symbol) [0x00810EA1]\n\t(No symbol) [0x0080EE80]\n\t(No symbol) [0x0080F81B]\n\t(No symbol) [0x00823FFE]\n\t(No symbol) [0x008AF217]\n\t(No symbol) [0x0088D29C]\n\t(No symbol) [0x008AE61B]\n\t(No symbol) [0x0088D096]\n\t(No symbol) [0x0085C840]\n\t(No symbol) [0x0085D6A4]\n\tGetHandleVerifier [0x00C84523+2701795]\n\tGetHandleVerifier [0x00C7FCA6+2683238]\n\tGetHandleVerifier [0x00C9A9EE+2793134]\n\tGetHandleVerifier [0x00A168C5+155013]\n\tGetHandleVerifier [0x00A1CFAD+181357]\n\tGetHandleVerifier [0x00A07458+92440]\n\tGetHandleVerifier [0x00A07600+92864]\n\tGetHandleVerifier [0x009F1FF0+5296]\n\tBaseThreadInitThunk [0x76E4FCC9+25]\n\tRtlGetAppContainerNamedObjectPath [0x775E82AE+286]\n\tRtlGetAppContainerNamedObjectPath [0x775E827E+238]\n\n", "trace": "  File \"D:\\automation-exercise-webapp\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\automation-exercise-webapp\\venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"D:\\automation-exercise-webapp\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\automation-exercise-webapp\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\automation-exercise-webapp\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"D:\\automation-exercise-webapp\\testCases\\conftest.py\", line 43, in browser\n    driver.get(config.BASE_URL)\n  File \"D:\\automation-exercise-webapp\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 454, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"D:\\automation-exercise-webapp\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\automation-exercise-webapp\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1748282426686, "stop": 1748282445122}], "start": 1748282426686, "stop": 1748282445184}